### ISSUE TITLE
What technology/idea are you most excited about?

### ISSUE THREAD

**Issue by mattzaitley** [drewminns/ama#10]
What tech/concept are you most excited about in web dev?

**Comment by drewminns** [comment]
PostCSS. Hands down.

The ability to have interchangeable tools for writing CSS is unreal. Particularly, the ability to write future CSS spec style code now with CSSNext.

These are a few of the plugins that I really love.
- [Rucksack](https://github.com/simplaio/rucksack)
- [Pseudo-class-enter](https://github.com/jonathantneal/postcss-pseudo-class-enter)
- [Quantity Queries](https://github.com/pascalduez/postcss-quantity-queries) :heart_eyes: 
- [Canadian Style Sheets](https://github.com/chancancode/postcss-canadian-stylesheets) :wink:
