### ISSUE TITLE
px or em based media queries?

### ISSUE THREAD

**Issue by fixmysync** [drewminns/ama#12]
I can't decide - I keep flip flopping back and forth on every new project! What is your current preference?

**Comment by drewminns** [comment]
EM! All the way. I've been a huge fan of [Juice](http://juicynex.us/juice/) mixins for that reason. They're all written for me!

Usage:

```
html {
  font-size: 62.5%;
  @include bp(medium) {
   font-size: 80%;
  }
}

// outputs
html {
  font-size: 62.5%;
}

@media (max-width: 64em) {
  html {
    font-size: 80%;
  }
}
```
