### ISSUE TITLE
What is your all-time favorite guitar solo?

### ISSUE THREAD

**Issue by darrinhenein** [drewminns/ama#13]
Bonus points for youtube/soundcloud link ;)

**Comment by drewminns** [comment]
Hands down, it's November Rain by Guns n' Roses. But not the first happy one, it's all about the massive solo at the end. So EPIC!

Click it!
[![ScreenShot](http://img.youtube.com/vi/8SbUC-UaAxE/0.jpg)](https://youtu.be/8SbUC-UaAxE?t=7m16s)
