### ISSUE TITLE
What are some of your favourite Chrome Extensions for Web Development and Design?

### ISSUE THREAD

**Issue by stephLaba** [drewminns/ama#14]

**Comment by drewminns** [comment]
The chrome extensions I use the most are the ones I forget are there.

Big fan of:
- http://www.typesample.com/
- [CSS Shapes Editor](https://chrome.google.com/webstore/detail/css-shapes-editor/nenndldnbcncjmeacmnondmkkfedmgmp)
- [Panda](https://chrome.google.com/webstore/detail/panda-4-news-inspiration/haafibkemckmbknhfkiiniobjpgkebko)
- [Postman for API](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop)
- [React Detector](https://chrome.google.com/webstore/detail/react-detector/jaaklebbenondhkanegppccanebkdjlh)
- [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)
- [Scratch JS](https://chrome.google.com/webstore/detail/scratch-js/alploljligeomonipppgaahpkenfnfkn)
- [JSON Formatter](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa)
- [DO IT](https://chrome.google.com/webstore/detail/do-it/eppncnmppghbndacgkideegigaminkfg) - (That's a personal favourite)
