### ISSUE TITLE
How do you maintain your energy teaching for 5-6 hours a day?

### ISSUE THREAD

**Issue by darcyclarke** [drewminns/ama#2]
After teaching at Humber and doing a number of presentations over the years, I can't understand how you're able to keep up your energy doing workshops or teaching for a full day. Do you have any tips/tricks? I would probably loose my voice or pass out at the 3hr mark.

**Comment by drewminns** [comment]
This is so cheesy, but excitement.

I thrive on others energy, so if people are stoked, I'm stoked. On the other side, I guess natural entertainer. I love being in front of people, so it's a bit of a plus for me to talk for eight hours.

It's absolutely not a job for extreme introverts, or people who don't thrive on others energy.
