### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [drewminns/ama#5]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by drewminns** [comment]
Funny enough, I really only use Sunrise, Mail, Twitter, Slack and Messages the most.

![img_0275](https://cloud.githubusercontent.com/assets/448452/8623943/87053d58-2702-11e5-8a62-876803940e59.PNG)
