### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [drewminns/ama#6]
Editor, terminal, themes, fonts, etc.

**Comment by drewminns** [comment]
I'm pretty much a stereotype of a developer with my environment.
- Sublime Text 3 with [Material Theme](http://equinusocio.github.io/material-theme/)
- iTerm with zsh and powerline
- Firefox Dev Edition/Chrome Canary
- Gulp
- Sass or PostCSS
- Node/WordPress/Rails
- Jekyll
- Markdown
- React/Angular
- [Hemingway](http://www.hemingwayapp.com/) (for writing. I'm apparently too passive)
